teams = {
    "Arizona Cardinals": "CRD",
    "Atlanta Falcons": "ATL",
    "Baltimore Ravens": "RAV",
    "Buffalo Bills": "BUF",
    "Carolina Panthers": "CAR",
    "Chicago Bears": "CHI",
    "Cincinnati Bengals": "CIN",
    "Cleveland Browns": "CLE",
    "Dallas Cowboys": "DAL",
    "Denver Broncos": "DEN",
    "Detroit Lions": "DET",
    "Green Bay Packers": "GNB",
    "Houston Texans": "HTX",
    "Indianapolis Colts": "CLT",
    "Jacksonville Jaguars": "JAX",
    "Kansas City Chiefs": "KAN",
    "Miami Dolphins": "MIA",
    "Minnesota Vikings": "MIN",
    "New England Patriots": "NWE",
    "New Orleans Saints": "NOR",
    "New York Giants": "NYG",
    "New York Jets": "NYJ",
    "Oakland Raiders": "RAI",
    "Philadelphia Eagles": "PHI",
    "Pittsburgh Steelers": "PIT",
    "St. Louis Rams": "RAM",
    "Los Angeles Rams": "RAM",
    "San Diego Chargers": "SDG",
    "Los Angeles Chargers": "SDG",
    "San Francisco 49ers": "SFO",
    "Seattle Seahawks": "SEA",
    "Tampa Bay Buccaneers": "TAM",
    "Tennessee Titans": "OTI",
    "Washington Redskins": "WAS"
}

keys = [
    'week',
    'day',
    'date',
    'time',
    '',
    'win_loss',
    'OT',
    'rec',
    'away',
    'opponent',
    'team_score',
    'opponent_score',
    'team_1st_downs',
    'team_total_yards',
    'team_pass_yards',
    'team_rush_yards',
    'team_turnovers',
    'opp_1st_downs',
    'opp_total_yards',
    'opp_pass_yards',
    'opp_rush_yards',
    'opp_turnovers',
]
